---
baseurl: "http://www.embryo-systems.info/"
languageCode: "en-us"
title: "Embryo Systems"

pygmentsuseclasses: false
pygmentsstyle: pastie

metaDataFormat: "yaml"

menu:
    main:
        - Name: "Source"
          Weight: -110
          Identifier: "source"
          URL: "https://github.com/nrdufour/orange"
---
